[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@openzepplin/=lib/openzepplin-contracts/contracts/","@ccip/=lib/ccip/",'@chainlink-local/=lib/chainlink-local/']

rpc_endpoints = { eth = "${SEPOLIA_URL}", arb = "${ARB_SEPOLIA_URL}", zksync = "https://sepolia.era.zksync.dev"}


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
